### PR TITLE
Reduce one traversal by "--"

### PR DESCRIPTION
**Pull request by zhongwencool**

### CODE REVIEW

**Comment by pichi** [comment]
Did anybody measured efficiency effect of this change or you just assume?

**Comment by zhongwencool** [comment]
I just read this code and assume, but I measured this as you mention, 
I was *WRONG*, but I don't know why...
```
16> List = lists:seq(1,1000000).
[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,
 23,24,25,26,27,28,29|...]
17> {T2, _} = timer:tc(fun() -> [X||X<-[List -- [1000000]]] end).
{48854,
 [[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,
   23,24,25,26|...]]}
18> {T1, _} = timer:tc(fun() -> [X||X<-List, X=/= 1000000] end).
{1312040,
 [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,
  23,24,25,26,27|...]}
19> (T1 - T2)/T2.
25.856347484341097
```

**Comment by pichi** [comment]
@zhongwencool: It's simple. `erlang:'--'/2` is BIF e.g. implemented in C. Using the filter in lists comprehension made it Elang code. Your approach decreases memory allocation little bit, but an effect due to GC should be negligible.

**Comment by zhongwencool** [comment]
@pichi how to explain T3? I get confused..

```erlang
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V9.0  (abort with ^G)
1> Max = 1000000.
1000000
2> List = lists:seq(1,Max).
[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,
 23,24,25,26,27,28,29|...]
3> {T1, _} = timer:tc(fun() -> [X||X<-List, X=/= Max] end).
{1627765,
 [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,
  23,24,25,26,27|...]}
4> {T3, _} = timer:tc(fun() -> [X||X<-[List -- [Max]],X =/= Max] end).
{63098,
 [[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,
   23,24,25,26|...]]}
5> (T1-T3)/T3.
24.797410377508005
```

**Comment by zhongwencool** [comment]
I find out what's wrong with T3 and T2.
I make a mistake to write `(List -- [Max])` to `[List -- [Max]]`
so the right is 
```erlang
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V9.0  (abort with ^G)
1> Max = 1000000.
1000000
2> List = lists:seq(1,Max).
[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,
 23,24,25,26,27,28,29|...]
3> {T1, _} = timer:tc(fun() -> [X||X<-List, X=/= Max] end).
{1633258,
 [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,
  23,24,25,26,27|...]}
4> {T2, _} = timer:tc(fun() -> [X||X<-(List -- [Max])] end).
{574409,
 [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,
  23,24,25,26,27|...]}
5> T1/T2
2.8433711867327984
6> {T3, _} = timer:tc(fun() -> [X||X<-(List -- [Max]),X =/= (Max-1)] end).
{2214516,
 [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,
  23,24,25,26,27|...]}
8> T1/T3.
0.7375236846335723
```

**Comment by ferd** [comment]
- the benchmark should be run with compiled code
- the benchmark should be run with https://github.com/jlouis/eministat

**Comment by zhongwencool** [comment]
@ferd Thanks for advice, 
The results suggest that the change should be positive.
I run the benchmark as  follow.

```erlang

-module(lists_comprehension).

-export([t/2]).

-define(SAMPLE_COUNT, 50).
-export([datasets/2, control/3]).

'with--'(0, _, _) -> ok;
'with--'(K, Max, List) ->
    [X||X<-(List -- [Max])],
    'with--'(K-1, Max, List).

'with_=/='(0, _, _) -> ok;
'with_=/='(K, Max, List) ->
    [X||X<-List, X=/= Max],
    'with_=/='(K-1, Max, List).

control(0, _, _) -> ok;
control(K, Max, Data) ->
    control(K-1, Max, Data).

datasets(Seq, Loop) ->
    Data = lists:seq(1, Seq),
    [
        eministat:s("--", fun() -> 'with--'(Loop, Seq, Data) end, ?SAMPLE_COUNT, us),
        eministat:s("=/=", fun() -> 'with_=/='(Loop, Seq, Data) end, ?SAMPLE_COUNT, us),
        eministat:s("control", fun() -> control(Loop, Seq, Data) end, ?SAMPLE_COUNT, us)
    ].

t(Seq, Loop) ->
    [Without | RelativeTo] = datasets(Seq, Loop),
    eministat:x(95.0, Without, RelativeTo).
```
```erlang
1> lists_comprehension:t(5000,1000).
x --
+ =/=
* control
+--------------------------------------------------------------------------+
|*                       ++++                                  xxxxxxxxxxxx|
|*                       +++                                   xxxxxxx xx x|
|*                       +++                                   xxxxxxx  x x|
|*                       + +                                   xxxxx x     |
|*                       + +                                   xxxx        |
|*                       +                                     x xx        |
|*                       +                                     x x         |
|*                       +                                     x           |
|*                       +                                     x           |
|*                       +                                     x           |
|*                       +                                     x           |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                       +                                                 |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|                                                              |__MA__|    |
|                       |A|                                                |
|A                                                                         |
+--------------------------------------------------------------------------+
Dataset: x N=50 CI=95.0000
Statistic     Value     [         Bias] (Bootstrapped LB‥UB)
Min:         7.50620e+4
1st Qu.      7.62950e+4
Median:      7.85490e+4
3rd Qu.      8.29010e+4
Max:         8.88300e+4
Average:     7.98994e+4 [     -1.99504] (   7.88353e+4 ‥    8.11637e+4)
Std. Dev:       4142.30 [     -54.5163] (      3500.02 ‥       4836.22)

Outliers: 0/0 = 0 (μ=7.98974e+4, σ=4087.79)
        Outlier variance:      0.344932 (moderate)

------

Dataset: + N=50 CI=95.0000
Statistic     Value     [         Bias] (Bootstrapped LB‥UB)
Min:         2.86100e+4
1st Qu.      2.88390e+4
Median:      2.90450e+4
3rd Qu.      2.93280e+4
Max:         3.26090e+4
Average:     2.94260e+4 [      1.32394] (   2.91974e+4 ‥    2.97590e+4)
Std. Dev:       1001.27 [     -20.2304] (      731.695 ‥       1308.57)

Outliers: 0/8 = 8 (μ=2.94273e+4, σ=981.040)
        Outlier variance:      0.189204 (moderate)

Difference at 95.0% confidence
        -5.04734e+4 ± 1195.72
        -63.1712% ± 1.49653%
        (Student's t, pooled s = 3013.40)
------

Dataset: * N=50 CI=95.0000
Statistic     Value     [         Bias] (Bootstrapped LB‥UB)
Min:            5.00000
1st Qu.         5.00000
Median:         5.00000
3rd Qu.         6.00000
Max:            6.00000
Average:        5.50000 [   1.88000e-4] (      5.34000 ‥       5.62000)
Std. Dev:      0.505076 [  -5.10524e-3] (     0.504672 ‥      0.505076)

Outliers: 0/0 = 0 (μ=5.50019, σ=0.499971)
        Outlier variance:      0.624822 (severe, the data set is probably unusable)

Difference at 95.0% confidence
        -7.98939e+4 ± 1162.25
        -99.9931% ± 1.45464%
        (Student's t, pooled s = 2929.05)
------
ok
2> lists_comprehension:t(10000,1000).
x --
+ =/=
* control
+--------------------------------------------------------------------------+
|*                      +++++++  + ++                           xxxxx x x x|
|*                      ++++++     +                            xxx x x x x|
|*                      ++ +                                    xxx x      |
|*                      ++ +                                    xxx        |
|*                      ++                                      xxx        |
|*                      ++                                      xxx        |
|*                      ++                                      xxx        |
|*                      ++                                      xx         |
|*                      ++                                      xx         |
|*                      ++                                      xx         |
|*                      +                                       xx         |
|*                      +                                       xx         |
|*                      +                                        x         |
|*                      +                                        x         |
|*                      +                                        x         |
|*                      +                                        x         |
|*                      +                                        x         |
|*                      +                                        x         |
|*                      +                                        x         |
|*                      +                                        x         |
|*                      +                                        x         |
|*                      +                                                  |
|*                      +                                                  |
|*                      +                                                  |
|*                      +                                                  |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|*                                                                         |
|                                                              |_MA_|      |
|                      |M_A__|                                             |
|A                                                                         |
+--------------------------------------------------------------------------+
Dataset: x N=50 CI=95.0000
Statistic     Value     [         Bias] (Bootstrapped LB‥UB)
Min:         1.58101e+5
1st Qu.      1.60067e+5
Median:      1.61015e+5
3rd Qu.      1.64160e+5
Max:         1.84012e+5
Average:     1.63564e+5 [     -5.22186] (   1.62137e+5 ‥    1.65743e+5)
Std. Dev:       6353.20 [     -156.561] (      4551.17 ‥       8501.25)

Outliers: 0/6 = 6 (μ=1.63558e+5, σ=6196.63)
        Outlier variance:      0.228069 (moderate)

------

Dataset: + N=50 CI=95.0000
Statistic     Value     [         Bias] (Bootstrapped LB‥UB)
Min:         5.75960e+4
1st Qu.      5.80070e+4
Median:      5.90860e+4
3rd Qu.      6.56610e+4
Max:         8.82870e+4
Average:     6.26864e+4 [      2.76309] (   6.09833e+4 ‥    6.53906e+4)
Std. Dev:       7692.20 [     -183.256] (      5398.08 ‥    1.03990e+4)

Outliers: 0/4 = 4 (μ=6.26891e+4, σ=7508.94)
        Outlier variance:      0.748013 (severe, the data set is probably unusable)

Difference at 95.0% confidence
        -1.00877e+5 ± 2799.24
        -61.6746% ± 1.71141%
        (Student's t, pooled s = 7054.54)
------

Dataset: * N=50 CI=95.0000
Statistic     Value     [         Bias] (Bootstrapped LB‥UB)
Min:            5.00000
1st Qu.         5.00000
Median:         6.00000
3rd Qu.         7.00000
Max:            36.0000
Average:        7.66000 [   4.10000e-4] (      6.58000 ‥       9.88000)
Std. Dev:       5.46084 [    -0.313137] (      2.70298 ‥       9.62361)

Outliers: 0/7 = 7 (μ=7.66041, σ=5.14771)
        Outlier variance:      0.979409 (severe, the data set is probably unusable)

Difference at 95.0% confidence
        -1.63556e+5 ± 1782.58
        -99.9953% ± 1.08984%
        (Student's t, pooled s = 4492.39)
------
ok
```

**Comment by ferd** [comment]
alright, sounds like the change should stay in then.

**Pull request merged**
