### PR TITLE
Adapt README.md to move from Travis CI to GitHub Actions

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**

### CODE REVIEW

**Comment by ferd** [comment]
Hm. Do we need a neater config to see the PR status within the PR page? Or is this gonna be incoming on a follow-up PR?

**Comment by paulo-ferraz-oliveira** [comment]
I don't understand your question. By "PR status" do you mean the GitHub Action stuff? i.e. "All checks have passed"?

**Comment by ferd** [comment]
Oh yeah. I don't know why I didn't notice them. I'm too tired for today. I was over-focused on "this branch has not been deployed" and got so used to the green checkmark I just ignored it.

**Comment by paulo-ferraz-oliveira** [comment]
It sometimes takes a while for the "checks" stuff to show up. You were just too fast 😄

**Pull request merged**
