### PR TITLE
Use pairing heap for finding top n in a list

### PR DESCRIPTION
**Pull request by pichi**
Using pairing heap is significantly faster than inserting into a sorted list. See over [there](https://gist.github.com/pichi/4d01443dc65e3fd6cc3784ec6998c16b).

_I knew it! I knew it, there once come a day when my pairing heap implementation becomes useful in some practical usage._

### CODE REVIEW

**Comment by zhongwencool** [comment]
Wow! it's unimaginable fast.

**Comment by pichi** [comment]
Yep, it's amazing. It is even faster than `lists:sort/1` up to top 20%.

```
> rp(test:test()).
[{{5000,5},
  [{pheap_____________________,165,100.0},
   {small_to_big_order_list_v2,359,217.57575757575756},
   {gb_tree___________________,419,253.93939393939397},
   {all_sorted_sublist________,3318,2010.909090909091}]},
 {{5000,50},
  [{pheap_____________________,489,100.0},
   {gb_tree___________________,686,140.28629856850716},
   {small_to_big_order_list_v2,812,166.05316973415134},
   {all_sorted_sublist________,2637,539.2638036809816}]},
 {{5000,500},
  [{pheap_____________________,1345,100.0},
   {gb_tree___________________,2314,172.04460966542752},
   {all_sorted_sublist________,3105,230.8550185873606},
   {small_to_big_order_list_v2,19495,1449.442379182156}]},
 {{5000,1000},
  [{pheap_____________________,2259,100.0},
   {all_sorted_sublist________,2495,110.44710048694112},
   {gb_tree___________________,3329,147.3660911907924},
   {small_to_big_order_list_v2,57600,2549.800796812749}]},
 {{10000,10},
  [{pheap_____________________,417,100.0},
   {small_to_big_order_list_v2,820,196.64268585131893},
   {gb_tree___________________,1030,247.00239808153478},
   {all_sorted_sublist________,6852,1643.1654676258993}]},
 {{10000,100},
  [{pheap_____________________,795,100.0},
   {gb_tree___________________,1540,193.71069182389937},
   {small_to_big_order_list_v2,2300,289.3081761006289},
   {all_sorted_sublist________,7048,886.5408805031446}]},
 {{10000,1000},
  [{pheap_____________________,3683,100.0},
   {gb_tree___________________,5023,136.38338311159382},
   {all_sorted_sublist________,6889,187.04860168341025},
   {small_to_big_order_list_v2,81587,2215.232147705675}]},
 {{10000,2000},
  [{pheap_____________________,5323,100.0},
   {all_sorted_sublist________,6692,125.71857974826226},
   {gb_tree___________________,7993,150.15968438850274},
   {small_to_big_order_list_v2,235716,4428.254743565658}]},
 {{20000,20},
  [{pheap_____________________,1550,100.0},
   {small_to_big_order_list_v2,1958,126.32258064516128},
   {gb_tree___________________,2258,145.67741935483872},
   {all_sorted_sublist________,13642,880.1290322580645}]},
 {{20000,200},
  [{pheap_____________________,2263,100.0},
   {gb_tree___________________,3485,153.99911621741052},
   {small_to_big_order_list_v2,7526,332.56738842244806},
   {all_sorted_sublist________,12860,568.2722050375608}]},
 {{20000,2000},
  [{pheap_____________________,6984,100.0},
   {gb_tree___________________,11044,158.1328751431844},
   {all_sorted_sublist________,13491,193.1701030927835},
   {small_to_big_order_list_v2,314242,4499.455899198167}]},
 {{20000,4000},
  [{pheap_____________________,13129,100.0},
   {all_sorted_sublist________,13456,102.4906695102445},
   {gb_tree___________________,17309,131.83791606367583},
   {small_to_big_order_list_v2,952423,7254.345342371849}]}]
ok
```

**Comment by redink** [comment]
@pichi 
I have added function `run_ordered_set_ets`, just like `run_gb_trees` but use ETS table. The test result is interesting. 
But, my `test_big` is not suitable for most scenarios, just for fun. 😃

**Comment by pichi** [comment]
Yes, using ets could be interesting in some scenarios but I consider it too much heavy weight for usage in tools like recon.

**Comment by pichi** [comment]
New results with some [tweaks](https://gist.github.com/pichi/cbe9bc51f5c3c09eca370bb2f95bb7a1).
Tweaking with `min_heap_size` shows that GC is what killing performance with bigger `TopNum` but `ets` is simply faster for bigger values.

```
> rp(test:test()).
[{{5000,5},
  [{pheap_____________________,199,100.0},
   {ordered_set_ets___________,549,275.8793969849246},
   {gb_tree___________________,806,405.0251256281407},
   {all_sorted_sublist________,3837,1928.1407035175878}]},
 {{5000,50},
  [{pheap_____________________,299,100.0},
   {ordered_set_ets___________,617,206.35451505016724},
   {gb_tree___________________,729,243.81270903010034},
   {all_sorted_sublist________,2482,830.1003344481605}]},
 {{5000,500},
  [{ordered_set_ets___________,1267,100.0},
   {pheap_____________________,2203,173.8752959747435},
   {all_sorted_sublist________,2704,213.4175217048145},
   {gb_tree___________________,4552,359.2738752959748}]},
 {{5000,1000},
  [{ordered_set_ets___________,1676,100.0},
   {pheap_____________________,2307,137.6491646778043},
   {gb_tree___________________,3381,201.73031026252985},
   {all_sorted_sublist________,4473,266.8854415274463}]},
 {{5000,2500},
  [{ordered_set_ets___________,2535,100.0},
   {all_sorted_sublist________,2768,109.19132149901381},
   {pheap_____________________,4257,167.92899408284023},
   {gb_tree___________________,7752,305.7988165680473}]},
 {{10000,10},
  [{pheap_____________________,414,100.0},
   {gb_tree___________________,1008,243.47826086956525},
   {ordered_set_ets___________,1019,246.13526570048307},
   {all_sorted_sublist________,8795,2124.3961352657007}]},
 {{10000,100},
  [{pheap_____________________,891,100.0},
   {ordered_set_ets___________,1258,141.18967452300785},
   {gb_tree___________________,2389,268.1257014590348},
   {all_sorted_sublist________,6321,709.4276094276095}]},
 {{10000,1000},
  [{ordered_set_ets___________,2604,100.0},
   {pheap_____________________,4766,183.02611367127497},
   {gb_tree___________________,5024,192.93394777265743},
   {all_sorted_sublist________,6974,267.81874039938555}]},
 {{10000,2000},
  [{ordered_set_ets___________,3388,100.0},
   {pheap_____________________,7044,207.91027154663516},
   {all_sorted_sublist________,7198,212.45572609208972},
   {gb_tree___________________,7759,229.01416765053128}]},
 {{10000,5000},
  [{ordered_set_ets___________,5084,100.0},
   {all_sorted_sublist________,8111,159.53973249409913},
   {pheap_____________________,9741,191.6011014948859},
   {gb_tree___________________,15121,297.42328874901654}]},
 {{15000,15},
  [{pheap_____________________,598,100.0},
   {ordered_set_ets___________,1539,257.3578595317726},
   {gb_tree___________________,1586,265.2173913043478},
   {all_sorted_sublist________,18330,3065.2173913043475}]},
 {{15000,150},
  [{pheap_____________________,1158,100.0},
   {ordered_set_ets___________,1860,160.6217616580311},
   {gb_tree___________________,2548,220.03454231433506},
   {all_sorted_sublist________,13784,1190.3281519861832}]},
 {{15000,1500},
  [{ordered_set_ets___________,3943,100.0},
   {pheap_____________________,4946,125.43748414912503},
   {gb_tree___________________,9093,230.61120973877757},
   {all_sorted_sublist________,11640,295.20669540958664}]},
 {{15000,3000},
  [{ordered_set_ets___________,5226,100.0},
   {pheap_____________________,10102,193.3027171833142},
   {gb_tree___________________,12723,243.45579793340985},
   {all_sorted_sublist________,14112,270.03444316877153}]},
 {{15000,7500},
  [{ordered_set_ets___________,7627,100.0},
   {all_sorted_sublist________,12213,160.12849088763602},
   {pheap_____________________,16367,214.59289366723482},
   {gb_tree___________________,24052,315.35334994099907}]},
 {{20000,20},
  [{pheap_____________________,1422,100.0},
   {ordered_set_ets___________,2280,160.33755274261603},
   {gb_tree___________________,2494,175.38677918424753},
   {all_sorted_sublist________,15228,1070.886075949367}]},
 {{20000,200},
  [{pheap_____________________,2070,100.0},
   {ordered_set_ets___________,2520,121.73913043478262},
   {gb_tree___________________,3583,173.09178743961354},
   {all_sorted_sublist________,17632,851.7874396135265}]},
 {{20000,2000},
  [{ordered_set_ets___________,5308,100.0},
   {pheap_____________________,11278,212.47174076865107},
   {gb_tree___________________,12154,228.97513187641297},
   {all_sorted_sublist________,18679,351.90278824415975}]},
 {{20000,4000},
  [{pheap_____________________,15581,100.0},
   {all_sorted_sublist________,15878,101.9061677684359},
   {ordered_set_ets___________,17219,110.51280405622232},
   {gb_tree___________________,22418,143.88036711379243}]},
 {{20000,10000},
  [{ordered_set_ets___________,13103,100.0},
   {all_sorted_sublist________,16735,127.71884301305046},
   {pheap_____________________,29619,226.04747004502786},
   {gb_tree___________________,31976,244.03571701137145}]},
 {{25000,25},
  [{pheap_____________________,1109,100.0},
   {ordered_set_ets___________,2700,243.4625788999098},
   {gb_tree___________________,4067,366.726780883679},
   {all_sorted_sublist________,32554,2935.4373309287644}]},
 {{25000,250},
  [{pheap_____________________,2203,100.0},
   {ordered_set_ets___________,3519,159.73672265093055},
   {gb_tree___________________,4356,197.73036768043576},
   {all_sorted_sublist________,28157,1278.1207444394008}]},
 {{25000,2500},
  [{ordered_set_ets___________,6393,100.0},
   {pheap_____________________,9901,154.8725168152667},
   {gb_tree___________________,15658,244.92413577350226},
   {all_sorted_sublist________,24525,383.62271234162364}]},
 {{25000,5000},
  [{ordered_set_ets___________,10598,100.0},
   {pheap_____________________,17809,168.04113983770523},
   {gb_tree___________________,25581,241.37573127005095},
   {all_sorted_sublist________,27615,260.5680317040951}]},
 {{25000,12500},
  [{ordered_set_ets___________,14232,100.0},
   {all_sorted_sublist________,26378,185.34288926363126},
   {pheap_____________________,34690,243.74648679033166},
   {gb_tree___________________,40964,287.83024170882516}]}]
ok
```

**Comment by pichi** [comment]
pink @ferd ?

**Comment by redink** [comment]
>  it too much heavy weight for usage in tools like recon.
Sure, I can not agree more. I use `recon:proc_count` to get topN and the N =< 10 in common. It too heavy using ETS table.
So, I said just for fun.

**Comment by pichi** [comment]
In this range is `pheap` clear winner :smile: 

```
> rp(test:test()).
[{{5000,1},
  [{pheap_____________________,159,100.0},
   {run_small_to_big_order_list_v2,345,216.98113207547172},
   {gb_tree___________________,365,229.55974842767296},
   {ordered_set_ets___________,474,298.1132075471698},
   {all_sorted_sublist________,2712,1705.6603773584907}]},
 {{5000,2},
  [{pheap_____________________,160,100.0},
   {run_small_to_big_order_list_v2,341,213.125},
   {gb_tree___________________,401,250.625},
   {ordered_set_ets___________,480,300.0},
   {all_sorted_sublist________,2516,1572.5}]},
 {{5000,3},
  [{pheap_____________________,180,100.0},
   {run_small_to_big_order_list_v2,432,240.0},
   {ordered_set_ets___________,562,312.22222222222223},
   {gb_tree___________________,691,383.8888888888889},
   {all_sorted_sublist________,3661,2033.888888888889}]},
 {{5000,5},
  [{pheap_____________________,295,100.0},
   {gb_tree___________________,482,163.38983050847457},
   {run_small_to_big_order_list_v2,493,167.11864406779662},
   {ordered_set_ets___________,604,204.74576271186442},
   {all_sorted_sublist________,2476,839.3220338983051}]},
 {{5000,7},
  [{pheap_____________________,168,100.0},
   {run_small_to_big_order_list_v2,383,227.97619047619045},
   {gb_tree___________________,429,255.35714285714283},
   {ordered_set_ets___________,519,308.92857142857144},
   {all_sorted_sublist________,2528,1504.7619047619048}]},
 {{5000,10},
  [{pheap_____________________,176,100.0},
   {run_small_to_big_order_list_v2,366,207.95454545454547},
   {gb_tree___________________,467,265.34090909090907},
   {ordered_set_ets___________,553,314.20454545454544},
   {all_sorted_sublist________,2517,1430.1136363636363}]},
 {{5000,15},
  [{pheap_____________________,197,100.0},
   {run_small_to_big_order_list_v2,399,202.53807106598987},
   {ordered_set_ets___________,545,276.6497461928934},
   {gb_tree___________________,554,281.21827411167516},
   {all_sorted_sublist________,2636,1338.0710659898477}]},
 {{5000,20},
  [{pheap_____________________,216,100.0},
   {run_small_to_big_order_list_v2,438,202.77777777777777},
   {gb_tree___________________,547,253.24074074074073},
   {ordered_set_ets___________,557,257.8703703703704},
   {all_sorted_sublist________,3653,1691.203703703704}]},
 {{10000,1},
  [{pheap_____________________,385,100.0},
   {run_small_to_big_order_list_v2,767,199.22077922077924},
   {ordered_set_ets___________,954,247.79220779220782},
   {gb_tree___________________,1195,310.38961038961037},
   {all_sorted_sublist________,8192,2127.7922077922076}]},
 {{10000,2},
  [{pheap_____________________,394,100.0},
   {run_small_to_big_order_list_v2,789,200.253807106599},
   {gb_tree___________________,914,231.97969543147207},
   {ordered_set_ets___________,939,238.3248730964467},
   {all_sorted_sublist________,6765,1717.0050761421319}]},
 {{10000,3},
  [{pheap_____________________,393,100.0},
   {run_small_to_big_order_list_v2,774,196.94656488549617},
   {gb_tree___________________,904,230.02544529262087},
   {ordered_set_ets___________,944,240.20356234096693},
   {all_sorted_sublist________,6617,1683.7150127226462}]},
 {{10000,5},
  [{pheap_____________________,406,100.0},
   {run_small_to_big_order_list_v2,786,193.5960591133005},
   {ordered_set_ets___________,959,236.20689655172416},
   {gb_tree___________________,981,241.6256157635468},
   {all_sorted_sublist________,7253,1786.4532019704434}]},
 {{10000,7},
  [{pheap_____________________,413,100.0},
   {run_small_to_big_order_list_v2,802,194.18886198547216},
   {gb_tree___________________,944,228.57142857142856},
   {ordered_set_ets___________,982,237.772397094431},
   {all_sorted_sublist________,9080,2198.547215496368}]},
 {{10000,10},
  [{pheap_____________________,415,100.0},
   {run_small_to_big_order_list_v2,820,197.59036144578312},
   {ordered_set_ets___________,986,237.59036144578315},
   {gb_tree___________________,1059,255.18072289156626},
   {all_sorted_sublist________,7254,1747.9518072289156}]},
 {{10000,15},
  [{pheap_____________________,457,100.0},
   {run_small_to_big_order_list_v2,869,190.15317286652078},
   {ordered_set_ets___________,1042,228.0087527352298},
   {gb_tree___________________,1076,235.44857768052515},
   {all_sorted_sublist________,6345,1388.402625820569}]},
 {{10000,20},
  [{pheap_____________________,453,100.0},
   {run_small_to_big_order_list_v2,900,198.6754966887417},
   {gb_tree___________________,1115,246.13686534216333},
   {ordered_set_ets___________,1157,255.4083885209713},
   {all_sorted_sublist________,6112,1349.2273730684326}]},
 {{15000,1},
  [{pheap_____________________,557,100.0},
   {gb_tree___________________,1241,222.80071813285457},
   {ordered_set_ets___________,1429,256.55296229802514},
   {run_small_to_big_order_list_v2,1601,287.4326750448833},
   {all_sorted_sublist________,11867,2130.520646319569}]},
 {{15000,2},
  [{pheap_____________________,767,100.0},
   {run_small_to_big_order_list_v2,1147,149.54367666232073},
   {gb_tree___________________,1451,189.17861799217732},
   {ordered_set_ets___________,1576,205.47588005215124},
   {all_sorted_sublist________,10168,1325.6844850065188}]},
 {{15000,3},
  [{pheap_____________________,564,100.0},
   {run_small_to_big_order_list_v2,1072,190.0709219858156},
   {gb_tree___________________,1295,229.60992907801418},
   {ordered_set_ets___________,1396,247.51773049645388},
   {all_sorted_sublist________,9325,1653.3687943262412}]},
 {{15000,5},
  [{pheap_____________________,764,100.0},
   {run_small_to_big_order_list_v2,1168,152.87958115183247},
   {ordered_set_ets___________,1516,198.42931937172773},
   {gb_tree___________________,1789,234.16230366492147},
   {all_sorted_sublist________,11197,1465.5759162303666}]},
 {{15000,7},
  [{pheap_____________________,555,100.0},
   {run_small_to_big_order_list_v2,1099,198.018018018018},
   {gb_tree___________________,1409,253.87387387387386},
   {ordered_set_ets___________,1448,260.9009009009009},
   {all_sorted_sublist________,12738,2295.1351351351354}]},
 {{15000,10},
  [{pheap_____________________,573,100.0},
   {run_small_to_big_order_list_v2,1143,199.4764397905759},
   {gb_tree___________________,1413,246.59685863874347},
   {ordered_set_ets___________,1651,288.1326352530541},
   {all_sorted_sublist________,11325,1976.439790575916}]},
 {{15000,15},
  [{pheap_____________________,599,100.0},
   {gb_tree___________________,1464,244.40734557595994},
   {ordered_set_ets___________,1559,260.26711185308847},
   {run_small_to_big_order_list_v2,1640,273.78964941569285},
   {all_sorted_sublist________,12982,2167.278797996661}]},
 {{15000,20},
  [{pheap_____________________,610,100.0},
   {run_small_to_big_order_list_v2,1247,204.4262295081967},
   {gb_tree___________________,1557,255.24590163934425},
   {ordered_set_ets___________,1590,260.655737704918},
   {all_sorted_sublist________,10569,1732.6229508196723}]},
 {{20000,1},
  [{pheap_____________________,1239,100.0},
   {run_small_to_big_order_list_v2,1848,149.15254237288136},
   {ordered_set_ets___________,1955,157.78853914447134},
   {gb_tree___________________,3032,244.71347861178367},
   {all_sorted_sublist________,16546,1335.4317998385795}]},
 {{20000,2},
  [{pheap_____________________,1213,100.0},
   {ordered_set_ets___________,1853,152.76174773289367},
   {run_small_to_big_order_list_v2,2075,171.06347897774114},
   {gb_tree___________________,2958,243.85820280296784},
   {all_sorted_sublist________,13029,1074.113767518549}]},
 {{20000,3},
  [{pheap_____________________,1321,100.0},
   {ordered_set_ets___________,1865,141.18092354277064},
   {run_small_to_big_order_list_v2,2322,175.77592732778197},
   {gb_tree___________________,4201,318.01665404996214},
   {all_sorted_sublist________,17594,1331.8697956093868}]},
 {{20000,5},
  [{pheap_____________________,1350,100.0},
   {ordered_set_ets___________,1961,145.25925925925927},
   {gb_tree___________________,2239,165.85185185185185},
   {run_small_to_big_order_list_v2,2245,166.2962962962963},
   {all_sorted_sublist________,16067,1190.148148148148}]},
 {{20000,7},
  [{pheap_____________________,1364,100.0},
   {ordered_set_ets___________,1928,141.34897360703812},
   {gb_tree___________________,2311,169.42815249266863},
   {run_small_to_big_order_list_v2,3289,241.1290322580645},
   {all_sorted_sublist________,16083,1179.1055718475072}]},
 {{20000,10},
  [{ordered_set_ets___________,1944,100.0},
   {run_small_to_big_order_list_v2,1982,101.95473251028805},
   {gb_tree___________________,2352,120.98765432098766},
   {pheap_____________________,2871,147.6851851851852},
   {all_sorted_sublist________,13047,671.141975308642}]},
 {{20000,15},
  [{pheap_____________________,1377,100.0},
   {ordered_set_ets___________,1998,145.09803921568627},
   {run_small_to_big_order_list_v2,2318,168.33696441539578},
   {gb_tree___________________,2739,198.91067538126362},
   {all_sorted_sublist________,15145,1099.854756717502}]},
 {{20000,20},
  [{pheap_____________________,1460,100.0},
   {ordered_set_ets___________,2086,142.87671232876713},
   {gb_tree___________________,2516,172.32876712328766},
   {run_small_to_big_order_list_v2,2758,188.9041095890411},
   {all_sorted_sublist________,15126,1036.0273972602738}]},
 {{25000,1},
  [{pheap_____________________,932,100.0},
   {gb_tree___________________,2124,227.89699570815452},
   {run_small_to_big_order_list_v2,2453,263.19742489270385},
   {ordered_set_ets___________,2513,269.6351931330472},
   {all_sorted_sublist________,29569,3172.6394849785406}]},
 {{25000,2},
  [{pheap_____________________,1018,100.0},
   {ordered_set_ets___________,2385,234.28290766208252},
   {run_small_to_big_order_list_v2,2471,242.73084479371317},
   {gb_tree___________________,2892,284.0864440078585},
   {all_sorted_sublist________,25895,2543.713163064833}]},
 {{25000,3},
  [{pheap_____________________,987,100.0},
   {run_small_to_big_order_list_v2,2309,233.94123606889562},
   {gb_tree___________________,2311,234.14387031408305},
   {ordered_set_ets___________,2366,239.7163120567376},
   {all_sorted_sublist________,26245,2659.067882472138}]},
 {{25000,5},
  [{pheap_____________________,1082,100.0},
   {gb_tree___________________,2235,206.56192236598892},
   {ordered_set_ets___________,2387,220.60998151571164},
   {run_small_to_big_order_list_v2,2878,265.98890942698705},
   {all_sorted_sublist________,23692,2189.648798521257}]},
 {{25000,7},
  [{pheap_____________________,969,100.0},
   {run_small_to_big_order_list_v2,1985,204.85036119711043},
   {gb_tree___________________,2480,255.9339525283798},
   {ordered_set_ets___________,2573,265.531475748194},
   {all_sorted_sublist________,23229,2397.2136222910217}]},
 {{25000,10},
  [{pheap_____________________,1465,100.0},
   {run_small_to_big_order_list_v2,1983,135.35836177474403},
   {gb_tree___________________,2524,172.2866894197952},
   {ordered_set_ets___________,2571,175.49488054607508},
   {all_sorted_sublist________,25869,1765.80204778157}]},
 {{25000,15},
  [{pheap_____________________,1044,100.0},
   {gb_tree___________________,2478,237.35632183908044},
   {ordered_set_ets___________,2633,252.20306513409963},
   {run_small_to_big_order_list_v2,2875,275.3831417624521},
   {all_sorted_sublist________,23981,2297.0306513409964}]},
 {{25000,20},
  [{pheap_____________________,998,100.0},
   {run_small_to_big_order_list_v2,2089,209.3186372745491},
   {ordered_set_ets___________,2462,246.6933867735471},
   {gb_tree___________________,2583,258.8176352705411},
   {all_sorted_sublist________,24249,2429.759519038076}]}]
ok
```

**Comment by redink** [comment]
I recommend `pheap` in `recon`.

**Comment by ferd** [comment]
I was on vacation away from computers, I'll take a look at this soon-ish.

**Pull request merged**
